### PR TITLE
I'm going inverted

### PR DESCRIPTION
**Pull request by privatezero**
Addresses https://github.com/amiaopensource/vrecord/issues/632 - could use some testing - I'll do some more on my end as well, but have only been able to use virtual inputs so far.

inverted

### CODE REVIEW

**Review by dericed — APPROVED** [review]
LGTM, but i added to this PR, so back at you

**Review by privatezero — COMMENTED** [review]
No reason from a code perspective, _report works fine on my end. I think that maybe from a user perspective, _report's output isn't quite as obvious (at least with default colors on my shell)

image (using _report)
 vs.
image (prior to change)

What do you think?

**Comment by dericed** [comment]
oh, thx for showing the difference, maybe in the _report function we could have -w and -W when we need to emphasize

**Comment by privatezero** [comment]
@dericed, added an option to _report that gives red background with white text on my end - should probably test and make sure it gives same outputs on your terminal.

**Comment by retokromer** [comment]
I personally would strongly suggest to **not** increase the possibilities. On the contrary, I guess, it would be better to reduce, in order to make our software better suitable for (partial) colourblind people. In my opinion, the focus on the different possibilities should always have a good **contrast** between background and text. The use of regular font and bold could be a possibility to differentiate different steps of warning or error, if really needed.

**Comment by privatezero** [comment]
Hi @retokromer, the current tweaks to alert color are an attempt to retain the exact same output as is in the current vrecord release, which is much higher contrast than if the `_report` function is left unmodified.

@dericed simplified the code by shifting that particular warning to use the standardized `_report` function (the function that is used for pretty much all the other warnings). That had the unfortunate effect of actually significantly decreasing the contrast for this alert (without expanding the function the warning is just red text), so I'm working to change the function to maintain the current output. Unfortunately, so far the latest tweak results in high contrast on my terminal but poor contrast on macOS, so this solution will have to be improved a bit.

**Comment by retokromer** [comment]
@privatezero Indeed! My remark was meant to go even a step further, suggesting to consider colour impaired people. On my end, it’s not just an academic exercise. There is a person in our staff, who cannot benefit entirely from the colour use in `vrecord` (of course he can consider just the actual text).

**Comment by dericed** [comment]
I suppose an issue could be opened on use of color, but I don't consider this blocking the PR about handling inversion of audio channels.

**Comment by retokromer** [comment]
No, it’s not blocking at all on my end. My remarks came to mind, because we often discuss this issues at our lab.

**Comment by privatezero** [comment]
Merging this - will have to rethink some warning in general, but that seems out of scope of this PR

**Pull request merged**
