### PR TITLE
add mkvtoolnix dependency in doc

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by kieranjol** [comment]
Where is it used exactly? I couldn't find any example of mkvpropedit, is there another mkv tool in there?

**Comment by dericed** [comment]
I think it’s preemptive as an unfinished pull request adds the requirement.

**Comment by retokromer** [comment]
Yes, it’s related to https://github.com/amiaopensource/vrecord/pull/264 and see https://github.com/amiaopensource/homebrew-amiaos/pull/90 as well.

**Comment by retokromer** [comment]
@kieranjol The exact source is https://github.com/amiaopensource/vrecord/pull/264/commits/db27f4087fdebd45227a639034b1e53f7430c96c.

**Comment by aeschweik** [comment]
Merged #264, making this PR applicable. Thanks @retokromer !

**Pull request merged**
