### PR TITLE
Split fields view

### PR DESCRIPTION
**Pull request by aeschweik**
for testing!

### CODE REVIEW

**Comment by bturkus** [comment]
soo amazing! I'll test tomorrow for sure. thanks!

**Comment by bturkus** [comment]
Hey @aeschweik, 
I just tried testing the split-fields-view, and while I'm not 100% that I did all the github stuff correctly, I couldn't get it to work. I see Split Fields as an option, but when I hit "6," nothing seems to happen. Possibly it's a key binding issue?
Thanks again for working on this!

**Comment by richardpl** [comment]
It does not work at all, __;__ can not be used as separator, also horizontal stacking needs yuv444 format, also __il__ filter should deinterleave both luma and chroma.

**Comment by aeschweik** [comment]
Hi, sorry, was out at the end of last week - thanks for the testing, the mistakes are definitely on my end and I'll be working more on it this week!

**Comment by aeschweik** [comment]
@bturkus et al - mind taking another pass with the last two commits? (Fingers crossed it works on another computer this time!)

**Comment by aeschweik** [comment]
@bturkus et al - mind taking another pass with the last two commits? (Fingers crossed it works on another computer this time!)

**Comment by bturkus** [comment]
hi @aeschweik sorry I slept on this. I just tested, and it seems to be working well. Thanks again! I do feel kinda stupid though: what exactly is going on in the diff quadrants, particularly the bottom ones? 

screen shot 2018-03-22 at 3 20 12 pm

**Comment by richardpl** [comment]
Top left is field split, top right is same, but only Y, bottom is same but for U and V component only.

**Pull request merged**
