### PR TITLE
Added TFF field order support for PAL

### PR DESCRIPTION
**Pull request by kieranjol**
tested with PAL, not sure if it will work on NTSC?

### CODE REVIEW

**Comment by dericed** [comment]
That seems like the right approach, but .... is all output of decklink in NTSC as bff and all output of decklink in PAL as tff? @jfarbowitz, was there another PAL tester to verify?

**Comment by kieranjol** [comment]
I've only ingested minidv via Firewire using the dv codec, but perhaps sdi out of pal minidv should be bottom field first? I think minidv is the only pal bff.

**Comment by jfarbowitz** [comment]
Yes, but they probably won't be able to test until next week.

**Comment by jfarbowitz** [comment]
Just analyzed a PAL video file from Bern in ffprobe and got this message:

top_field_first=0

**Comment by dericed** [comment]
but that's how it labels, can you get how it looks `ffmpeg -i feelthebern.mkv -vf idet -f null -`

**Comment by jfarbowitz** [comment]
Is this what you're looking for from ffmpeg? 

```
[null @ 0x7fd079014000] Encoder did not produce proper pts, making some up.
frame= 3000 fps=296 q=-0.0 Lsize=N/A time=00:02:00.00 bitrate=N/A    
video:281kB audio:22500kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_idet_0 @ 0x7fd078d00000] Repeated Fields: Neither:  2990 Top:     5 Bottom:     5
[Parsed_idet_0 @ 0x7fd078d00000] Single frame detection: TFF:   312 BFF:   379 Progressive:     0 Undetermined:  2309
[Parsed_idet_0 @ 0x7fd078d00000] Multi frame detection: TFF:   799 BFF:  2194 Progressive:     0 Undetermined:     7
```

**Comment by dericed** [comment]
You're data suggests that it is bottom field first, but TFF=799 and BFF=2194 seems odd, usually one value wins by a much larger margin.

**Comment by kieranjol** [comment]
This is probably meaningless, but here's the idet filter's output on the SD PAL film transfer I did. I set incorporated my patch which creates a TFF interlaced field order. I guess diet is noticing that both fields are identical as it's a film source? The film was a little shrunk so I thought that there would be more noticeable fluctutations between fields. Haven't been able to put tape through yet.

ffmpeg log via vrecord: https://gist.github.com/kieranjol/a4add620785a21aac84a

ifis-mac-pro:~ ifiedit$ ffmpeg -i /Volumes/TK\ transfers/af4633_overend_collection_roll_13_onelight/AF4633_overend_collection_roll_13_onelight.mov -vf idet -f null -
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.2_1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfreetype --enable-ffplay --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Volumes/TK transfers/af4633_overend_collection_roll_13_onelight/AF4633_overend_collection_roll_13_onelight.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf56.40.101
  Duration: 00:12:02.24, start: 0.000000, bitrate: 223491 kb/s
    Stream #0:0(eng): Video: v210 (v210 / 0x30313276), yuv422p10le, 720x576, 221184 kb/s, SAR 16:15 DAR 4:3, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : DataHandler
      encoder         : Uncompressed 10-bit 4:2:2
    Stream #0:1(eng): Audio: pcm_s24le (in24 / 0x34326E69), 48000 Hz, stereo, s32 (24 bit), 2304 kb/s (default)
    Metadata:
      handler_name    : DataHandler
Output #0, null, to 'pipe:':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf56.36.100
    Stream #0:0(eng): Video: rawvideo (Y3[10][10] / 0xA0A3359), yuv422p10le, 720x576 [SAR 16:15 DAR 4:3], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      handler_name    : DataHandler
      encoder         : Lavc56.41.100 rawvideo
    Stream #0:1(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16 (24 bit), 1536 kb/s (default)
    Metadata:
      handler_name    : DataHandler
      encoder         : Lavc56.41.100 pcm_s16le
Stream mapping:
  Stream #0:0 -> #0:0 (v210 (native) -> rawvideo (native))
  Stream #0:1 -> #0:1 (pcm_s24le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
[null @ 0x7fb593011000] Encoder did not produce proper pts, making some up.
frame=18056 fps= 65 q=0.0 Lsize=N/A time=00:12:02.24 bitrate=N/A    
video:1693kB audio:135412kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_idet_0 @ 0x7fb592501460] Repeated Fields: Neither: 18056 Top:     0 Bottom:     0
[Parsed_idet_0 @ 0x7fb592501460] Single frame detection: TFF:     1 BFF:     4 Progressive: 11811 Undetermined:  6240
[Parsed_idet_0 @ 0x7fb592501460] Multi frame detection: TFF:     0 BFF:     0 Progressive: 18056 Undetermined:     0
ifis-mac-pro:~ ifiedit$

**Pull request merged**
