### PR TITLE
add frame positioning video for horizontal calibration

### PR DESCRIPTION
**Pull request by dericed**
resolves https://github.com/amiaopensource/vrecord/issues/603

### CODE REVIEW

**Comment by bturkus** [comment]
thanks for working on this! seems really great, but a few thoughts:

- wondering if we could change the default background color from black to something like yellow or cyan. tired this out with smpte bars, and the black bar on the far right made it difficult for me to determine the best position. see here:
Screen Shot 2021-08-02 at 3 24 19 PM

- hard for me to describe exactly what's going on, but in testing I found that I was only able to get passthrough mode to work correctly one time. after closing and quitting vrecord, when I would relaunch and select passthrough, ffplay wouldn't pop up. I think something is getting held up somewhere, but can't quite figure out why this is occurring.

**Comment by dericed** [comment]
Hey @bturkus, the ffplay issue is fixed in https://github.com/amiaopensource/vrecord/pull/681 (I hope). I changed the labels to dark gray for clarity.

**Review by bturkus — COMMENTED** [review]
lgtm sorry for the DELAY

**Review by bturkus — APPROVED** [review]
approved!

**Pull request merged**
