### PR TITLE
force overlay to yuv444 in this case

### PR DESCRIPTION
**Pull request by dericed**
fixes https://github.com/amiaopensource/vrecord/issues/566 with ffmpeg 4.3 and 4.3.1

### CODE REVIEW

**Comment by privatezero** [comment]
this is working on my end as well!

**Comment by retokromer** [comment]
I suggest to make a new release, because this is a bug fix.

**Comment by privatezero** [comment]
Agree, but this should be merged first - https://github.com/amiaopensource/vrecord/pull/570

**Comment by retokromer** [comment]
Yep.

**Pull request merged**
