### PR TITLE
add extra step is ffmpeg capture with mpv player

### PR DESCRIPTION
**Pull request by dericed**
should fix https://github.com/amiaopensource/vrecord/issues/652

### CODE REVIEW

**Review by privatezero — APPROVED** [review]
LGTM, but I'm dead in the water regarding Blackmagic access to needs a test from @bturkus

**Review by retokromer — APPROVED** [review]
just
```
((VRECORD_STEPS++))
```
should have the same effect

**Review by bturkus — APPROVED** [review]
lgtm!

**Comment by bturkus** [comment]
thank you!

**Pull request merged**
