### PR TITLE
Refactor how passthrough and record commands are prepared

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
ugh, surprised that after all this work the script is only one line shorter. At any rate, this is a beast of a refactor to handle setting up the commands for playback and record in the _setup_vrecord_process function. This will lead to the gtkdialog environment being able to use this information directly. Overall the intent of this PR was to refactor but not change behavior but a few inconsistencies have been cleaned up in the process.

**Comment by bturkus** [comment]
Trying this out now. Initial things I'm seeing:
- passthrough doesn't seem to be functional, whether pulled up from the GUI or vrecord -p
- capture I'm getting the following error: `vrecord command Error: invalid VRECORD_STEPS value of 1`

**Comment by dericed** [comment]
That's not good. Can you re-run with `./vrecord -e -G` and copy/paste the debug box over here.

**Comment by bturkus** [comment]
trying this and not getting any error messages other than the invalid VRECORD_STEPS value of 1

**Comment by dericed** [comment]
oh, do you mind directing your testing to https://github.com/amiaopensource/vrecord/pull/591?

**Comment by dericed** [comment]
closing as this is being broken up into smaller PRs

**Pull request closed without merging**
