### PR TITLE
uniform syntax

### PR DESCRIPTION
**Pull request by retokromer**
- add `#` info at the beginning
- improve version in help message
- always use `_report` instead of `echo`
- uniform `exit` values
- delete not needed escaping of CR/LF
- alignment

### CODE REVIEW

**Comment by privatezero** [comment]
I just took a look, and it looks like mm isn't actually listed as a dependency of vrecord?

**Comment by retokromer** [comment]
Hmm… good point! This should be added, as a partial use of `mm` was already there.

**Comment by retokromer** [comment]
No, I am wrong! The two functions of `mm` it uses (i.e. `_report` and `_get_iso8601`) are implemented directly into `vrecord`.

**Comment by privatezero** [comment]
Oh nice!

**Pull request merged**
