### PR TITLE
add analog rca and xlr options

### PR DESCRIPTION
**Pull request by dericed**
resolves https://github.com/amiaopensource/vrecord/issues/404

### CODE REVIEW

**Comment by privatezero** [comment]
Shouldn't the option for generic 'analog' be removed to avoid possible confusion since the addition of more specific options basically supersedes it?

**Comment by privatezero** [comment]
On that note - it might be a good idea to add the line levels in the config settings so something like:

`RCA Inputs (-10 dBv)`
`XLR Inputs (+4 dBu)`

To make things a little clearer on when people should be using which setting?

**Comment by retokromer** [comment]
nit: is it `dBv` in the USA? EBU uses `dBV`.

**Comment by privatezero** [comment]
No - you are correct! Should be `-10 dBV`

**Comment by dericed** [comment]
@privatezero, not sure about adding static line level measurements such as -10 and +4. This would need some testing to ensure that custom line level alternations added in the Desktop Video application are not used in vrecord. For instance if RCA input default is -10 but someone adjusts this in Desktop Video and vrecord does use it, then we shouldn't report -10 as it could be misleading.

Also I'd prefer to leave the Analog option since many users are accustomed to it. And it allows switching between the breakdown cables without necessarily having to adjust the audio input setting.

**Comment by privatezero** [comment]
@dericed, are you referring to the custom input gain settings in Desktop Video? I agree that would be a problem if those gain settings are passed through to vrecord without the user's knowledge (and indeed some testing should probably be done for that), but that doesn't relate the the line level settings which will always be either -10 dBV or +4 dBu depending on source.

Has there been any testing to confirm that using the generic `analog` setting within the FFmpeg device  actually does  in fact does select the correct input levels automatically depending on which breakout cable is being used?

**Comment by dericed** [comment]
updated based on @privatezero feedback, but with my UltraStudio Express I get this if I select either analog_xlr or analog_rca:

```
[decklink @ 0x7fbb5c8a0200] Device does not support selected audio input.
[decklink @ 0x7fbb5c8a0200] Could not set input configuration
UltraStudio Express: Input/output error
```

I haven't found a way to detect what inputs are supported by the connected device.

**Comment by dericed** [comment]
This commit is updated to include a method of testing whether or not the listed audio and video inputs are supported by the hardware. Please re-review.

**Comment by retokromer** [comment]
ping

**Comment by privatezero** [comment]
Somehow missed this update! I'll give it a test tonight for the new 'scan inputs' button. I can confirm reproducing the original behavior of the Blackmagic card used for testing being unable to select anything beyond the generic analog input.

**Comment by dericed** [comment]
rebasing upon https://github.com/amiaopensource/vrecord/pull/489

**Comment by privatezero** [comment]
Just tested - the scan inputs button works once, but upon second click seems to fire up the passthrough mode for some reason

**Pull request closed without merging**
