### PR TITLE
deck control integration

### PR DESCRIPTION
**Pull request by dericed**
ping @genfhk @bturkus 
For testing, this requires `brew install amiaopensource/amiaos/deckcontrol` until the vrecord installer is updated.
untested

### CODE REVIEW

**Comment by jshupeGitHub** [comment]
deck control is a wonderFUL idea

**Comment by dericed** [comment]
@jshupeGitHub, do you have access to hardware to test this?

**Comment by jshupeGitHub** [comment]
i suppose that i do,
I now have 2 ubuntu 18.04 syetems that .....run vrecord 
and I have , many, sony vtr 

what are you thinking , suggesting?

**Comment by jshupeGitHub** [comment]
i suppose I would need to use an extrem card or decklink sdi ....the mini recorder has no mach cntrl...
unless it would be possible to talk out com1 of pc........

**Comment by retokromer** [comment]
>i suppose I would need to use an extrem card or decklink sdi ....the mini recorder has no mach cntrl...

We have a [Needed Hardware](https://github.com/amiaopensource/vrecord/blob/master/Resources/Documentation/hardware.md) page in the documentation. If there are any updates, please let us know. Thank you!

**Comment by dericed** [comment]
@jshupeGitHub, @retokromer 
To test this, you need an RS422 connection from the deck to the blackmagic card. If you have that then you can run `brew install amiaopensource/amiaos/deckcontrol` and run vrecord from this PR. You should then get buttons and a status bar to control the deck for testing.

**Comment by retokromer** [comment]
If I remember carefully, the UltraStudio models have an RS-422 connector, but I don’t have any of them here at home and therefore currently I cannot test this.

**Comment by retokromer** [comment]
>For testing, this requires `brew install amiaopensource/amiaos/deckcontrol` until the vrecord installer is updated.For testing, this requires brew install amiaopensource/amiaos/deckcontrol until the vrecord installer is updated.

@dericed Do you plan to make it optional in the formula?

**Comment by dericed** [comment]
updated and ready. Here's a screenshot
image

**Pull request merged**
