### PR TITLE
use geq to highlight max/min val and out of range vals

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by richardpl** [comment]
geq is slooow.

**Comment by dericed** [comment]
lutyuv?

**Comment by richardpl** [comment]
Yes, also geq is 8bit only.

**Comment by retokromer** [comment]
Ping! This is approaching one year…

**Comment by dericed** [comment]
dropping this, the idea could be redone in lutyuv but as noted geq does slow it down too much

**Comment by retokromer** [comment]
@dericed: OK, thanks. I’ll check if there is any idea in de-restorer that may be recycled for improving speed here.

**Comment by retokromer** [comment]
@dericed : This branch is still alive. Do you plan to replace the `geq` filter by `lutyuv`? Or should this be moved into a "wish" issue?

**Pull request closed without merging**
