### PR TITLE
update release date

### PR DESCRIPTION
**Pull request by privatezero**

### CODE REVIEW

**Review by retokromer — APPROVED** [review]

**Comment by retokromer** [comment]
@privatezero : By chance, did you check if FFmpeg a version < 5 is needed, or if the current version 5.0 works fine? I am asking for the Homebrew formula.

**Comment by privatezero** [comment]
@retokromer haven't been able to fully test building with version 5 - I'm having some issues getting my new UltraStudio Mini to play nicely on Ubuntu, so still can't actually run a full test.

I can say that audio mode seems to work fine with FFmpeg 5.0 on my end

**Comment by retokromer** [comment]
@privatezero Thank you! Then I prefer to wait for some additional days before merging the upgraded `ffmpegdecklink` formula.

**Comment by privatezero** [comment]
@dericed - we good to merge and make a release?

**Comment by retokromer** [comment]
@dericed FYI: On my end I tested “only” on Debian and Ubuntu, but not on macOS.

**Review by dericed — APPROVED** [review]

**Pull request merged**
