### PR TITLE
Further changes for linux/docs

### PR DESCRIPTION
**Pull request by privatezero**
* Fixes problem with `gzcat` vs `zcat`
* Starts more detailed instructions for full install on Linux

### CODE REVIEW

**Comment by retokromer** [comment]
@privatezero Do you really need to install dependencies with `apt-get` on your end? 

(We use since two years or so (version `0.7.28`) Debian in production und Ubuntu a little in production but more for teaching.)

**Comment by privatezero** [comment]
@retokromer, yes, I have had rotten luck with having linuxbrew complete full/sustainable installs on my end, usually due to tangled dependencies, which has led me to favor `apt-get` when possible. Are you saying you have had no problems with a full install using only the vrecord brew formula?

**Comment by retokromer** [comment]
@privatezero Our installation script sets up working stations with various software elements we use for AV preservation, including vrecord. I will be back at the lab by end of next week and can check the order of the installations and possible dependencies between them. In general, today we have less difficulties with Linux (Debian) than with macOS, that’s for sure.

**Comment by retokromer** [comment]
@privatezero I just run a test and I confirm that on my end I can install vrecord on Debian using only brew.

**Comment by privatezero** [comment]
Thanks for the follow-up @retokromer, I'll have to spin up a Debian machine and see if it works better than Ubuntu for me!

**Pull request merged**
