### PR TITLE
use alternate mediainfo expressions for BT.470 B/G

### PR DESCRIPTION
**Pull request by dericed**
syncing to https://github.com/MediaArea/MediaInfoLib/commit/c75a5f3a864c92ee472b706ba362677f5f0a4697

addresses https://github.com/amiaopensource/vrecord/issues/349

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Sorry about the regression, definitely need to find a better method for changing some display. Maybe use a "OR" in case the policy is used with an older version.

**Comment by dericed** [comment]
good point @JeromeMartinez. AFK just now, but this pr should be updated to support either expression.

**Comment by bturkus** [comment]
tested, and looks good. thanks for the quick fix!

**Comment by dericed** [comment]
@bturkus, this is updated to @JeromeMartinez's suggestion, please re-review.

**Pull request merged**
