### PR TITLE
Smaller updates

### PR DESCRIPTION
**Pull request by dericed**
This is a subset of https://github.com/amiaopensource/vrecord/pull/591 to make review/testing easier.

### CODE REVIEW

**Review by retokromer — APPROVED** [review]
reading the code LGTM (sorry, I can test only next week)

**Comment by bturkus** [comment]
I've tested DV passthrough and capture, and Decklink (ffmpeg and bmd) passthrough and capture, and all seem good. 

Two things: (1) RS422 doesnt seem to be working (but DV works fine), and (2) BMD capture to FFV1/MKV fails MediaConch (this might not be new but wanted to point it out).

Thanks!

**Comment by dericed** [comment]
what was the mediaconch fail? do you have the output?

**Review by privatezero — APPROVED** [review]

**Comment by dericed** [comment]
Merging but @bturkus, let’s follow up on your comments.

**Pull request merged**
