### PR TITLE
adds an avfoundation input option to vrecord

### PR DESCRIPTION
**Pull request by dericed**
supports capture from DV devices. The options are very limited to focus on piping the dv stream from the input to output, so the interface is a lot simpler than that for decklink. Rewrapping to a container could be added as a post-process later.

### CODE REVIEW

**Comment by dericed** [comment]
documentation is needed for this before merge

**Comment by dericed** [comment]
It's a closed issue but this PR would resolve https://github.com/amiaopensource/vrecord/issues/322 since the device input is not the decklink input.

**Comment by dericed** [comment]
going to merge, @libbyhopfauf will follow with a PR for the documentation before the next release.

**Comment by libbyhopfauf** [comment]
on it!

**Pull request merged**
