### PR TITLE
Make monitoring audiomapping more representative

### PR DESCRIPTION
**Pull request by privatezero**
This should make it so what you see/hear for audio and audio scopes during preview and capture maps exactly to what has been selected in the GUI. Should resolve https://github.com/amiaopensource/vrecord/issues/773

### CODE REVIEW

**Comment by privatezero** [comment]
@dericed - have you had a chance to test to see if this works on mac?

**Comment by privatezero** [comment]
ping @amiaopensource/vrecord-maintainers

**Comment by bturkus** [comment]
I will totally test this on Thursday if no one gets to it sooner. An important addition!

**Comment by privatezero** [comment]
thanks @bturkus!

**Comment by bturkus** [comment]
Hi @privatezero testing this out now and I think it seems good. Tried swapping between having CHs 1&2 tone or muted, same with 3&4, and jumped bet capturing just 1&2 or just 3&4. All of the QCTools jpgs looked good, except I was little confused by this one, which is CHs 1&2 muted but 3&4 tone; is this what you would expect:

ben_12_34_QC_output_graphs

**Review by dericed — APPROVED** [review]

**Comment by privatezero** [comment]
Thanks for the test!

**Pull request merged**
