### PR TITLE
Aspect ratio

### PR DESCRIPTION
**Pull request by dericed**
This address https://github.com/amiaopensource/vrecord/issues/689. Some issues:

It's a breaking change. vrecord used to set both ntsc and pal to 4/3 (no 16/9 or other options). To force NTSC 720x486 to 4/3 used a PAR of 8/9 and for PAL at 720x576 would use a PAR of 16/15. In this version when the user wants a DAR of 4/3, then the PAR is 10/11 for NTSC and 12/11 for PAL. When the user wants 16/9, then it's a PAR of 40/33 for NTSC and 16/11 for PAL.

The default is set to 4/3 even if the user doesn't pick one.

I have a list of unrecommended PAR values at https://github.com/amiaopensource/vrecord/issues/689#issuecomment-2108256577, including the one that vrecord used before this PR, but I hesitate in putting unrecommended PAR values as user options.

I tried to look for standards on NTSC and PAL PAR, and bt601 seems to potentially be that, but it seems quite ignored by the video community, see https://en.wikipedia.org/wiki/Pixel_aspect_ratio#Pixel_aspect_ratios_of_common_video_formats.

### CODE REVIEW

**Comment by dericed** [comment]
Here's a picture of the adjustment to the interface. 
image

**Review by privatezero — COMMENTED** [review]
Bit of a typo in this and the following error message I think

**Comment by privatezero** [comment]
Haven't been able to live test this (my main video station has been apart for some repair work) but the code looks good to me and I agree with general conversation on https://github.com/amiaopensource/vrecord/issues/689

**Review by privatezero — APPROVED** [review]

**Comment by dericed** [comment]
Here's the look of SAR tuning under the config menu 

image

**Comment by dericed** [comment]
Lots of updates in here. Now on the main decklink page, is the 4/3 or 16/9 switch, but under config are the fine-tuning options for the 4 combinations of 4/3&16/9 with NTSC&PAL. I think I got all the SAR options discussed in https://github.com/amiaopensource/vrecord/issues/689.

**Comment by iamdamosuzuki** [comment]
This looks great. I haven't had a chance to test this but the screenshots of the settings windows look great.

**Pull request merged**
