### PR TITLE
finish swapping avfctl for dvrescue

### PR DESCRIPTION
**Pull request by dericed**
do not merge until after next dvrescue release

### CODE REVIEW

**Comment by dericed** [comment]
dvrescue release is out, this is ready for review

**Review by privatezero — CHANGES_REQUESTED** [review]
I just tested this out and I think that since we have shifted to dvrescue for our main capture mechanism on Linux as well, we should probably drop the system check/conditionals for `dvcont` here and just use the same deck control commands across systems.

**Comment by privatezero** [comment]
The one wonky thing I've found is repack doesn't work as expected on my end (although underlying command works OK when run outside of vrecord). I wonder if this is a shell version difference or something - does this work on your end?

**Review by privatezero — APPROVED** [review]
Hmm actually on second thought, it looks like it is throwing some weird messages into the CLI after exiting the GUI. I say let's just go ahead and merge this and I can maybe circle back later to look at the causes and confirm there are no big issues ditching dvcont.

**Pull request merged**
