### PR TITLE
move audio filter for mpv

### PR DESCRIPTION
**Pull request by retokromer**
resolves https://github.com/amiaopensource/vrecord/issues/166

### CODE REVIEW

**Comment by privatezero** [comment]
I probably will be around a black magic next week so possibly can test if someone else hasn't already!

**Comment by retokromer** [comment]
Thank you, @privatezero! I will wait.

**Comment by retokromer** [comment]
ping @libbyhopfauf

**Comment by retokromer** [comment]
I merge, please amend if needed.

**Comment by privatezero** [comment]
Hi @retokromer! I finally had access to a blackmagic today, and am able to confirm that the patch appears to be working as intended!

**Comment by retokromer** [comment]
Thank you for the feedback, @privatezero!

**Comment by libbyhopfauf** [comment]
I'm sorry for not responding to this previously! The audio check now seems to be working normally. Thank you @retokromer!!

**Pull request merged**
