### PR TITLE
Refactor conf and lookups

### PR DESCRIPTION
**Pull request by dericed**
needs testing but these two commits simplify the construction of the pashua configuration file and consolidation the functions that interepret the meaning of the user options.

### CODE REVIEW

**Comment by privatezero** [comment]
Seems to be functioning as intended! Anything specific you wanted tested out?

**Comment by dericed** [comment]
I guess i want to make sure that the added complexity is worth the line count reduction. This does reduce the need to repeat arrays of optional repeated though.

**Comment by privatezero** [comment]
cool! I'll play around with it a bit more on the internal end of things to see if I notice anything else

**Comment by retokromer** [comment]
>This does reduce the need to repeat arrays of optional repeated though.

That’s a good move, in my opinion (also in the optic of https://github.com/amiaopensource/vrecord/issues/282)!

**Pull request merged**
