### PR TITLE
add a Hardware page

### PR DESCRIPTION
**Pull request by retokromer**
Considering the current discussion on AMIA-L, a page about the needed hardware for the digitisation station would be useful.

cc @jfarbowitz

### CODE REVIEW

**Comment by dericed** [comment]
For vrecord I think the hardware needed is a computer running a recent Mac OS or Linux and Blackmagic card from:

- https://www.blackmagicdesign.com/products/ultrastudiothunderbolt
- https://www.blackmagicdesign.com/products/decklink
- https://www.blackmagicdesign.com/products/intensitypro4k
- https://www.blackmagicdesign.com/products/intensity

and whatever is necessary to connect that to the computer.

**Comment by retokromer** [comment]
Thank you, @dericed. I’ll improve a little the placeholder, and cross check it also with my Albanian pals Skip and Jonathan.

**Comment by jfarbowitz** [comment]
I've only ever seen vrecord run with with the Ultrastudio and the Decklink. Do we have confirmation that it will run on the Intensity?

Also, I know we tried Linux installations in the past and there were issues. Have those been resolved?

**Comment by retokromer** [comment]
Did we not use the Intensity in Tirana?

There are still issues on Linux, but many parts seem to work now. And there are big issues on Windows and so far it almost doesn't work (also I would like to use Ubuntu on Windows 10). In South-East Asia macOS is hardly ever used, bu they have a huge amount of analogue cassettes to digitise...

**Comment by TedLangdell** [comment]
According to Skip, it was an intensity shuttle thunderbolt addition on the $499 Mac Mini.

I've duplicated the same set up, and I'm using USB 3 Drive Successful Way to capture 8 bit YUV in an MOV wrapper using both the blackmagic  media express software and VRecord.

**Comment by jfarbowitz** [comment]
@retokromer, my mistake. We did use the Intensity in Tirana.

**Comment by retokromer** [comment]
No problem at all, @jfarbowitz, I was just unsure if I am mixing together different things. It happens…

**Pull request merged**
