### PR TITLE
make doc easier to maintain

### PR DESCRIPTION
**Pull request by retokromer**
You don’t need to renumber the other items when adding or deleting one.

### CODE REVIEW

**Comment by dericed** [comment]
I'm unsure. Maybe easier for some to maintain, but incrementing integers is well-known, and it's more confusing to read if unrendered.  @privatezero, any opinion?

**Comment by privatezero** [comment]
Yeah, I can see pluses and minuses. Just checked and the basic pandoc md to html conversion renders correctly with this edit, so if that route is taken in the future for local renders this doesn't affect things. Overall, I am OK with this change.

**Comment by retokromer** [comment]
Wider context FYI: The content was dissociated from the layout in HTML 3.2 (second half of the 1990s, if I remember carefully), introducing XML and CSS. We did it in order to simplify the work. [However, we didn’t imagine back then how relevant XML would become. The majority of us just considered SGML too complex and tried another route.]

With this change one can add, move or delete items from an ordered list without having to take care of the correct numbering.

@privatezero: Thanks for checking! I was quite sure `pandoc` would digest it correctly, but I didn’t test it…

**Comment by retokromer** [comment]
For reference: https://guides.github.com/features/mastering-markdown/

**Comment by privatezero** [comment]
Roger that, @retokromer

**Pull request merged**
