### PR TITLE
fix audio monitoring in DV mode

### PR DESCRIPTION
**Pull request by privatezero**
Fixes lack of audio in DV mode from empty filter error

### CODE REVIEW

**Comment by dericed** [comment]
untested but lgtm

**Comment by privatezero** [comment]
@dericed - good to merge?

**Review by dericed — APPROVED** [review]

**Comment by privatezero** [comment]
Will need to add some options (maybe a flag to mute audio) to avoid a total cacophony for anyone having multiple capture windows - I'm thinking I might integrate those into a PR integrating https://github.com/amiaopensource/vrecord/tree/logmeters and an option to switch audio meters between linear and logarithmic

**Comment by libbyhopfauf** [comment]
@privatezero Tested and looks great to me! Thank you!

**Pull request merged**
